repos:
  - repo: local
    hooks:
      - id: format
        name: ruff format
        entry: ruff format .
        language: system
        types: [python]
        pass_filenames: false
      - id: lint
        name: ruff check
        entry: ruff check --fix .
        language: system
        types: [python]
        pass_filenames: false
      - id: type-check
        name: ty
        entry: ty check .
        language: system
        types: [python]
        pass_filenames: false
